import os
from datetime import timedelta

class Config:
    #DATABASE CONFIGURATION
    SQLALCHEMY_DATABASE_URI = os.getenv('DATABASE_URL')
    SQLALCHEMY_TRACK_MODIFICATIONS = False

    #COGNITO CONFIGURATION
    COGNITO_REGION = 'us-east-1'
    COGNITO_USERPOOL_ID = os.getenv('COGNITO_USERPOOL_ID')
    COGNITO_APP_CLIENT_ID = os.getenv('COGNITO_APP_CLIENT_ID')
    COGNITO_CHECK_TOKEN_EXPIRATION = True
    COGNITO_JWT_HEADER_NAME = 'Authorization'
    COGNITO_JWT_HEADER_PREFIX = 'Bearer'
